services:
    # Admin
    external.synchronize.extension:
        class: ExternalBundle\Admin\SynchronizeAdminExtension
        arguments:
            - '@external.domain.synchronizer'

    # Command
    external.command.import-larp:
        class: ExternalBundle\Command\ImportLarpFromExternalCommand
        arguments:
            - '@external.domain.larp.provider'
            - '@external.domain.import.larp.importer'
        tags:
            - { name: console.command }

    external.command.import-persons:
        class: ExternalBundle\Command\ImportPersonsFromExternalCommand
        arguments:
            - '@external.domain.import.person.importer'
        tags:
            - { name: console.command }

    # Controller
    external.controller.user_connect:
        class: ExternalBundle\Controller\UserConnectController
        arguments:
            - '@external.domain.user.provider'
            - '@templating'
            - '@form.factory'
            - '@security.token_storage'
            - '@doctrine.orm.default_entity_manager'
            - '@router'

    external.controller.sync:
        class: ExternalBundle\Controller\SyncController
        arguments:
            - '@external.domain.synchronizer'
            - '@session'
            - '@translator'
            - '@router'

    # Domain

    ## Import

    ### Common

    #### Converter
    external.domain.import.converter.larp:
        class: ExternalBundle\Domain\Import\Common\Converter\EntityConverter
        arguments:
            - '@app.repository.larp'

    external.domain.import.converter.person:
        class: ExternalBundle\Domain\Import\Common\Converter\EntityConverter
        arguments:
            - '@app.repository.person'

    ### Larp
    external.domain.import.larp.importer:
        class: ExternalBundle\Domain\Import\Larp\Importer
        arguments:
            - '@doctrine.dbal.external_connection'
            - '@external.domain.import.larp.writer'

    external.domain.import.larp.writer:
        class: ExternalBundle\Domain\Import\Larp\Writer
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ### Person
    external.domain.import.person.importer:
        class: ExternalBundle\Domain\Import\Person\Importer
        arguments:
            - '@doctrine.dbal.external_connection'
            - '@external.domain.import.person.writer'

    external.domain.import.person.writer:
        class: ExternalBundle\Domain\Import\Person\Writer
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ### Organizer
    external.domain.import.organizer.importer:
        class: ExternalBundle\Domain\Import\Organizer\Importer
        arguments:
            - '@doctrine.dbal.external_connection'
            - '@external.domain.import.organizer.writer'
        calls:
            - [setPersonConverter, ['@external.domain.import.converter.person']]
            - [setLarpConverter, ['@external.domain.import.converter.larp']]
            - [setValidator, ['@validator']]

    external.domain.import.organizer.writer:
        class: ExternalBundle\Domain\Import\Organizer\Writer
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ## Larp
    external.domain.larp.provider:
        class: ExternalBundle\Domain\Larp\Provider
        arguments:
            - '@doctrine.dbal.external_connection'

    ## Synchronizer
    external.domain.synchronizer:
        class: ExternalBundle\Domain\Synchronizer\ChainSynchronizer
        tags:
            - { name: 'mmc.processor.chain' }

    external.domain.synchronizer.larp:
        class: ExternalBundle\Domain\Synchronizer\Synchronizer
        arguments:
            - '@external.domain.import.larp.importer'
        tags:
            - { name: 'external.domain.synchronizer' }

    external.domain.synchronizer.person:
        class: ExternalBundle\Domain\Synchronizer\Synchronizer
        arguments:
            - '@external.domain.import.person.importer'
        tags:
            - { name: 'external.domain.synchronizer' }

    external.domain.synchronizer.organizer:
        class: ExternalBundle\Domain\Synchronizer\OrganizerSynchronizer
        arguments:
            - '@external.domain.import.organizer.importer'
            - '@external.domain.import.larp.importer'
            - '@external.domain.import.person.importer'

        tags:
            - { name: 'external.domain.synchronizer' }

    ## User
    external.domain.user.provider:
        class: ExternalBundle\Domain\User\Provider
        arguments:
            - '@doctrine.dbal.external_connection'

    external.domain.user.connect.check_external_credentials_validator:
        class: ExternalBundle\Domain\User\Connect\CheckExternalCredentialsValidator
        arguments:
            - '@external.domain.user.provider'
            - '@app.repository.person'
            - '@external.domain.import.person.importer'
        tags:
            - { name: validator.constraint_validator }
