services:
    # Command
    external.command.import-larp:
        class: ExternalBundle\Command\ImportLarpFromExternalCommand
        arguments:
            - '@external.domain.larp.provider'
            - '@external.domain.import.larp.importer'
        tags:
            - { name: console.command }

    # Controller
    external.controller.user_connect:
        class: ExternalBundle\Controller\UserConnectController
        arguments:
            - '@external.domain.user.provider'
            - '@templating'
            - '@form.factory'
            - '@security.token_storage'
            - '@doctrine.orm.default_entity_manager'
            - '@router'

    # Domain

    ## Import
    external.domain.import.larp.importer:
        class: ExternalBundle\Domain\Import\Larp\Importer
        arguments:
            - '@doctrine.dbal.external_connection'
            - '@external.domain.import.larp.writer'

    external.domain.import.larp.writer:
        class: ExternalBundle\Domain\Import\Larp\Writer
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ## Larp
    external.domain.larp.provider:
        class: ExternalBundle\Domain\Larp\Provider
        arguments:
            - '@doctrine.dbal.external_connection'

    ## User
    external.domain.user.provider:
        class: ExternalBundle\Domain\User\Provider
        arguments:
            - '@doctrine.dbal.external_connection'

    external.domain.user.connect.check_external_credentials_validator:
        class: ExternalBundle\Domain\User\Connect\CheckExternalCredentialsValidator
        arguments:
            - '@external.domain.user.provider'
        tags:
            - { name: validator.constraint_validator }
