services:
    # Admin
    external.synchronize.extension:
        class: ExternalBundle\Admin\SynchronizeAdminExtension
        arguments:
            - '@external.mapping.external_properties_provider'
            - '@app.security.profile_provider'

    app.admin.synchronization:
        class: ExternalBundle\Admin\SynchronizationAdmin
        arguments: [~, ExternalBundle\Entity\Synchronization, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Synchronization }
        calls:
            - [ setTranslationDomain, [Synchronization]]
            - [ setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
        public: true

    # Command
    external.command.import-larp:
        class: ExternalBundle\Command\ImportLarpFromExternalCommand
        arguments:
            - '@external.domain.larp.provider'
            - '@external.domain.import.larp.importer_factory'
        tags:
            - { name: console.command }

    external.command.import-persons:
        class: ExternalBundle\Command\ImportPersonsFromExternalCommand
        arguments:
            - '@external.domain.import.person.importer_factory'
        tags:
            - { name: console.command }

    external.command.synchronize:
        class: ExternalBundle\Command\SynchronizeCommand
        arguments:
            - '@external.domain.orchestrator'
        tags:
            - { name: console.command }

    # Controller
    external.controller.user_connect:
        class: ExternalBundle\Controller\UserConnectController
        arguments:
            - '@external.domain.user.provider'
            - '@templating'
            - '@form.factory'
            - '@security.token_storage'
            - '@doctrine.orm.default_entity_manager'
            - '@router'

    external.controller.sync:
        class: ExternalBundle\Controller\SyncController
        arguments:
            - '@session'
            - '@translator'
            - '@router'
            - '@doctrine.orm.default_entity_manager'
            - '@serializer'

    # Domain

    ## Import

    ### Character
    external.domain.import.character.importer_factory:
        class: ExternalBundle\Domain\Import\Character\ImporterFactory
        arguments:
            - '@doctrine.dbal.external_connection'
            - '@external.domain.import.character.writer'
        calls:
            - [setPlayerConverter, ['@external.domain.import.converter.player']]
            - [setLarpConverter, ['@external.domain.import.converter.larp']]
            - [setValidator, ['@validator']]
            - [setEntityManager, ['@doctrine.orm.default_entity_manager']]

    external.domain.import.character.writer:
        class: ExternalBundle\Domain\Import\Character\Writer
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ### Common

    #### Converter
    external.domain.import.converter.larp:
        class: ExternalBundle\Domain\Import\Common\Converter\EntityConverter
        arguments:
            - '@app.repository.larp'

    external.domain.import.converter.person:
        class: ExternalBundle\Domain\Import\Common\Converter\EntityConverter
        arguments:
            - '@app.repository.person'

    external.domain.import.converter.player:
        class: ExternalBundle\Domain\Import\Player\PlayerConverter
        arguments:
            - '@app.repository.player'

    ### Group
    external.domain.import.group.importer_factory:
        class: ExternalBundle\Domain\Import\Group\ImporterFactory
        arguments:
            - '@doctrine.dbal.external_connection'
            - '@external.domain.import.group.writer'
        calls:
            - [setLarpConverter, ['@external.domain.import.converter.larp']]
            - [setValidator, ['@validator']]
            - [setEntityManager, ['@doctrine.orm.default_entity_manager']]

    external.domain.import.group.writer:
        class: ExternalBundle\Domain\Import\Group\Writer
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ### Larp
    external.domain.import.larp.importer_factory:
        class: ExternalBundle\Domain\Import\Larp\ImporterFactory
        arguments:
            - '@doctrine.dbal.external_connection'
            - '@external.domain.import.larp.writer'
        calls:
            - [setEntityManager, ['@doctrine.orm.default_entity_manager']]

    external.domain.import.larp.writer:
        class: ExternalBundle\Domain\Import\Larp\Writer
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ### Organizer
    external.domain.import.organizer.importer_factory:
        class: ExternalBundle\Domain\Import\Organizer\ImporterFactory
        arguments:
            - '@doctrine.dbal.external_connection'
            - '@external.domain.import.organizer.writer'
        calls:
            - [setPersonConverter, ['@external.domain.import.converter.person']]
            - [setLarpConverter, ['@external.domain.import.converter.larp']]
            - [setValidator, ['@validator']]
            - [setEntityManager, ['@doctrine.orm.default_entity_manager']]

    external.domain.import.organizer.writer:
        class: ExternalBundle\Domain\Import\Organizer\Writer
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ### Person
    external.domain.import.person.importer_factory:
        class: ExternalBundle\Domain\Import\Person\ImporterFactory
        arguments:
            - '@doctrine.dbal.external_connection'
            - '@external.domain.import.person.writer'
        calls:
            - [setEntityManager, ['@doctrine.orm.default_entity_manager']]

    external.domain.import.person.writer:
        class: ExternalBundle\Domain\Import\Person\Writer
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ### Player
    external.domain.import.player.importer_factory:
        class: ExternalBundle\Domain\Import\Player\ImporterFactory
        arguments:
            - '@doctrine.dbal.external_connection'
            - '@external.domain.import.player.writer'
        calls:
            - [setPersonConverter, ['@external.domain.import.converter.person']]
            - [setLarpConverter, ['@external.domain.import.converter.larp']]
            - [setValidator, ['@validator']]
            - [setEntityManager, ['@doctrine.orm.default_entity_manager']]

    external.domain.import.player.writer:
        class: ExternalBundle\Domain\Import\Player\Writer
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ## Larp
    external.domain.larp.provider:
        class: ExternalBundle\Domain\Larp\Provider
        arguments:
            - '@doctrine.dbal.external_connection'

    ## Mapping
    external.mapping.external_properties_provider:
        class: ExternalBundle\Domain\Mapping\ExternalPropertiesProvider

    ## Synchronizer
    external.domain.orchestrator:
        class: ExternalBundle\Domain\Synchronizer\Orchestrator
        arguments:
            - '@external.domain.synchronizer'
            - '@doctrine.orm.default_entity_manager'
            - '@serializer'

    external.domain.synchronizer:
        class: ExternalBundle\Domain\Synchronizer\ChainSynchronizer
        tags:
            - { name: 'mmc.processor.chain' }

    external.domain.synchronizer.character:
        class: ExternalBundle\Domain\Synchronizer\Synchronizer
        arguments:
            - '@external.domain.import.character.importer_factory'
        calls:
            - [addParentDependency, ['larp_id', '@external.domain.import.larp.importer_factory', 10]]
            - [addParentDependency, ['player_id', '@external.domain.import.player.importer_factory', 5]]

        tags:
            - { name: 'external.domain.synchronizer' }

    external.domain.synchronizer.group:
        class: ExternalBundle\Domain\Synchronizer\Synchronizer
        arguments:
            - '@external.domain.import.group.importer_factory'
        calls:
            - [addParentDependency, ['larp_id', '@external.domain.import.larp.importer_factory']]

        tags:
            - { name: 'external.domain.synchronizer' }

    external.domain.synchronizer.global_larp:
        class: ExternalBundle\Domain\Synchronizer\Synchronizer
        arguments:
            - '@external.domain.import.larp.importer_factory'
        calls:
            - [addParentDependency, ['person_id', '@external.domain.import.person.importer_factory']]
            - [addChildDependency, ['larp_id', '@external.domain.import.organizer.importer_factory', 10]]
            - [addChildDependency, ['larp_id', '@external.domain.import.group.importer_factory', 8]]
            - [addChildDependency, ['larp_id', '@external.domain.import.player.importer_factory', 6]]
            - [addChildDependency, ['larp_id', '@external.domain.import.character.importer_factory', 4]]
        tags:
            - { name: 'external.domain.synchronizer' }

    external.domain.synchronizer.larp:
        class: ExternalBundle\Domain\Synchronizer\Synchronizer
        arguments:
            - '@external.domain.import.larp.importer_factory'
        tags:
            - { name: 'external.domain.synchronizer' }

    external.domain.synchronizer.person:
        class: ExternalBundle\Domain\Synchronizer\Synchronizer
        arguments:
            - '@external.domain.import.person.importer_factory'
        tags:
            - { name: 'external.domain.synchronizer' }

    external.domain.synchronizer.organizer:
        class: ExternalBundle\Domain\Synchronizer\Synchronizer
        arguments:
            - '@external.domain.import.organizer.importer_factory'
        calls:
            - [addParentDependency, ['larp_id', '@external.domain.import.larp.importer_factory']]
            - [addParentDependency, ['person_id', '@external.domain.import.person.importer_factory']]

        tags:
            - { name: 'external.domain.synchronizer' }

    external.domain.synchronizer.player:
        class: ExternalBundle\Domain\Synchronizer\Synchronizer
        arguments:
            - '@external.domain.import.player.importer_factory'
        calls:
            - [addParentDependency, ['larp_id', '@external.domain.import.larp.importer_factory']]
            - [addParentDependency, ['person_id', '@external.domain.import.person.importer_factory']]
        tags:
            - { name: 'external.domain.synchronizer' }

    ## User
    external.domain.user.provider:
        class: ExternalBundle\Domain\User\Provider
        arguments:
            - '@doctrine.dbal.external_connection'

    external.domain.user.connect.check_external_credentials_validator:
        class: ExternalBundle\Domain\User\Connect\CheckExternalCredentialsValidator
        arguments:
            - '@external.domain.user.provider'
            - '@app.repository.person'
            - '@external.domain.import.person.importer_factory'
        tags:
            - { name: validator.constraint_validator }

    # Security
    external.security.voter.synchronization_admin:
        class: ExternalBundle\Security\Voter\SynchronizationAdminVoter
        arguments:
            - '@security.access.decision_manager'
        tags:
            - {name: security.voter}

    # Twig
    external.twig.extension:
        class: ExternalBundle\Twig\ExternalExtension
        arguments:
            - '@translator'
            - '@serializer'
        tags:
            - { name: twig.extension }
