services:
    #Command
    external.command.import-larp:
        class: ExternalBundle\Command\ImportLarpFromExternalCommand
        arguments:
            - '@external.domain.larp.provider'
            - '@external.domain.import.larp.importer'
        tags:
            - { name: console.command }

    #Domain
    external.domain.larp.provider:
        class: ExternalBundle\Domain\Larp\Provider
        arguments:
            - '@doctrine.dbal.external_connection'

    ## Import
    external.domain.import.larp.importer:
        class: ExternalBundle\Domain\Import\Larp\Importer
        arguments:
            - '@doctrine.dbal.external_connection'
            - '@external.domain.import.larp.writer'

    external.domain.import.larp.writer:
        class: ExternalBundle\Domain\Import\Larp\Writer
        arguments:
            - '@doctrine.orm.default_entity_manager'
