services:
    # Admin
    app.admin.character:
        class: AppBundle\Admin\CharacterAdmin
        arguments: [~, AppBundle\Entity\Character, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Character }
        calls:
            - [ setTranslationDomain, [Character]]
            - [ setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
            - [ addChild, ['@app.admin.character_group_for_character']]
            - [ addChild, ['@app.admin.character_organizer_for_character']]
            - [ setFormFactory, ['@app.doctrine.character_data_definition.form.factory']]
        public: true

    app.admin.character_data_definition:
        class: AppBundle\Admin\CharacterDataDefinitionAdmin
        arguments: [~, AppBundle\Entity\CharacterDataDefinition, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: CharacterDataDefinition }
        calls:
            - [ setTranslationDomain, [CharacterDataDefinition]]
            - [ setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
            - [ setSubClasses, [{
                string: AppBundle\Entity\CharacterDataDefinitionString,
                integer: AppBundle\Entity\CharacterDataDefinitionInteger
                }]]
        public: true

    app.admin.character_data_section:
        class: AppBundle\Admin\CharacterDataSectionAdmin
        arguments: [~, AppBundle\Entity\CharacterDataSection, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: CharacterDataSection }
        calls:
            - [ setTranslationDomain, [CharacterDataSection]]
            - [ setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
        public: true

    app.admin.character_group_for_character:
        class: AppBundle\Admin\CharacterGroupForCharacterAdmin
        arguments: [~, AppBundle\Entity\CharacterGroup, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: CharacterGroupForCharacter }
        calls:
            - [ setTranslationDomain, [CharacterGroupForCharacter]]
            - [ setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
        public: true

    app.admin.character_group_for_group:
        class: AppBundle\Admin\CharacterGroupForGroupAdmin
        arguments: [~, AppBundle\Entity\CharacterGroup, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: CharacterGroupForGroup }
        calls:
            - [ setTranslationDomain, [CharacterGroupForGroup]]
            - [ setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
        public: true

    app.admin.character_organizer_for_character:
        class: AppBundle\Admin\CharacterOrganizerForCharacterAdmin
        arguments: [~, AppBundle\Entity\CharacterOrganizer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: CharacterOrganizerForCharacter }
        calls:
            - [ setTranslationDomain, [CharacterOrganizerForCharacter]]
            - [ setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
        public: true

    app.admin.character_organizer_for_organizer:
        class: AppBundle\Admin\CharacterOrganizerForOrganizerAdmin
        arguments: [~, AppBundle\Entity\CharacterOrganizer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: CharacterOrganizerForOrganizer }
        calls:
            - [ setTranslationDomain, [CharacterOrganizerForOrganizer]]
            - [ setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
        public: true

    app.admin.group:
        class: AppBundle\Admin\GroupAdmin
        arguments: [~, AppBundle\Entity\Group, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Group }
        calls:
            - [ setTranslationDomain, [Group]]
            - [ setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
            - [ addChild, ['@app.admin.character_group_for_group']]
            - [ setCompositionProvider, ['@app.domain.group.composition_provider']]
        public: true

    app.admin.larp:
        class: AppBundle\Admin\LarpAdmin
        arguments: [~, AppBundle\Entity\Larp, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Larp }
        calls:
            - [ setTranslationDomain, [Larp]]
            - [ setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
        public: true

    app.admin.organizer:
        class: AppBundle\Admin\OrganizerAdmin
        arguments: [~, AppBundle\Entity\Organizer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Organizer }
        calls:
            - [ setTranslationDomain, [Organizer]]
            - [ setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
            - [ addChild, ['@app.admin.character_organizer_for_organizer']]
        public: true

    app.admin.person:
        class: AppBundle\Admin\PersonAdmin
        arguments: [~, AppBundle\Entity\Person, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Person }
        calls:
            - [ setTranslationDomain, [Person]]
            - [ setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
            - [ setTokenStorage, ['@security.token_storage']]
        public: true

    app.admin.player:
        class: AppBundle\Admin\PlayerAdmin
        arguments: [~, AppBundle\Entity\Player, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Player }
        calls:
            - [ setTranslationDomain, [Player]]
            - [ setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
        public: true

    # Block
    app.block.profile:
        class: 'AppBundle\Block\ProfileBlock'
        arguments:
            - app.block.profile
            - '@templating'
            - '@app.security.profile_provider'

        tags:
            - { name: sonata.block }

    # Extension
    app.extension.character_data_definition.integer:
        class: AppBundle\Admin\Extension\CharacterDataDefinitionIntegerExtension
        tags:
            - { name: sonata.admin.extension, target: app.admin.character_data_definition }

    app.extension.character_data_definition.string:
        class: AppBundle\Admin\Extension\CharacterDataDefinitionStringExtension
        tags:
            - { name: sonata.admin.extension, target: app.admin.character_data_definition }

    app.extension.larp:
        class: AppBundle\Admin\Extension\LarpExtension
        arguments:
            - '@app.security.profile_provider'

    # Filter
    admin.filter.insensitive_string:
        class: AppBundle\Admin\Filter\CaseInsensitiveStringFilter
        tags:
            - { name: sonata.admin.filter.type, alias: doctrine_orm_istring }

    # ModelManager
    sonata.admin.manager.orm:
        class: AppBundle\Admin\Model\ModelManager
        arguments:
            - '@doctrine'
