services:
    # Admin
    app.admin.larp:
        class: AppBundle\Admin\LarpAdmin
        arguments: [~, AppBundle\Entity\Larp, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Larp }
        calls:
            - [ setTranslationDomain, [Larp]]
            - [ setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
        public: true

    app.admin.person:
        class: AppBundle\Admin\PersonAdmin
        arguments: [~, AppBundle\Entity\Person, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Person }
        calls:
            - [ setTranslationDomain, [Person]]
            - [ setLabelTranslatorStrategy, ['@sonata.admin.label.strategy.underscore']]
            - [ setTokenStorage, ['@security.token_storage']]
        public: true

    # Block
    app.block.profile:
        class: 'AppBundle\Block\ProfileBlock'
        arguments:
            - app.block.profile
            - '@templating'
            - '@app.security.profile_provider'

        tags:
            - { name: sonata.block }

    # Filter
    admin.filter.insensitive_string:
        class: AppBundle\Admin\Filter\CaseInsensitiveStringFilter
        tags:
            - { name: sonata.admin.filter.type, alias: doctrine_orm_istring }
