services:
    app.security.profile_provider:
        class: AppBundle\Security\ProfileProvider
        arguments:
            - '@security.token_storage'
            - '@doctrine.orm.default_entity_manager'

    # Voter
    app.security.voter.character_admin:
        class: AppBundle\Security\Voter\CharacterAdminVoter
        arguments:
            - '@security.access.decision_manager'
            - '@app.security.profile_provider'
        tags:
            - {name: security.voter}

    app.security.voter.character_data_definition_admin:
        class: AppBundle\Security\Voter\CharacterDataDefinitionAdminVoter
        arguments:
            - '@security.access.decision_manager'
            - '@app.security.profile_provider'
        tags:
            - {name: security.voter}

    app.security.voter.character_data_section_admin:
        class: AppBundle\Security\Voter\CharacterDataSectionAdminVoter
        arguments:
            - '@security.access.decision_manager'
            - '@app.security.profile_provider'
        tags:
            - {name: security.voter}

    app.security.voter.character_organizer_admin:
        class: AppBundle\Security\Voter\CharacterOrganizerAdminVoter
        arguments:
            - '@security.access.decision_manager'
            - '@app.security.profile_provider'
        tags:
            - {name: security.voter}

    app.security.voter.character_group_admin:
        class: AppBundle\Security\Voter\CharacterGroupAdminVoter
        arguments:
            - '@security.access.decision_manager'
            - '@app.security.profile_provider'
        tags:
            - {name: security.voter}

    app.security.voter.group_admin:
        class: AppBundle\Security\Voter\GroupAdminVoter
        arguments:
            - '@security.access.decision_manager'
            - '@app.security.profile_provider'
        tags:
            - {name: security.voter}

    app.security.voter.larp_admin:
        class: AppBundle\Security\Voter\LarpAdminVoter
        arguments:
            - '@security.access.decision_manager'
        tags:
            - {name: security.voter}

    app.security.voter.organizer_admin:
        class: AppBundle\Security\Voter\OrganizerAdminVoter
        arguments:
            - '@security.access.decision_manager'
            - '@app.security.profile_provider'
        tags:
            - {name: security.voter}

    app.security.voter.person_admin:
        class: AppBundle\Security\Voter\PersonAdminVoter
        arguments:
            - '@security.access.decision_manager'
            - '@app.security.profile_provider'
        tags:
            - {name: security.voter}

    app.security.voter.player_admin:
        class: AppBundle\Security\Voter\PlayerAdminVoter
        arguments:
            - '@security.access.decision_manager'
            - '@app.security.profile_provider'
        tags:
            - {name: security.voter}
