services:
    # Domain

    ## Group
    app.domain.group.composition_provider:
        class: AppBundle\Domain\Group\CompositionProvider
        arguments:
            - '@app.repository.group'

    # Repository
    app.repository.character:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Character' ]

    app.repository.group:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Group' ]

    app.repository.larp:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Larp' ]

    app.repository.organizer:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Organizer' ]

    app.repository.person:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Person' ]

    app.repository.player:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Player' ]

    app.repository.skill:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Skill' ]
