services:
    # Doctrine
    ## Listeners
    app.doctrine.listeners.entity_loader:
        class: AppBundle\Doctrine\Listeners\EntityLoader
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: doctrine.event_listener, event: loadEntity }

    # Domain

    ## CharacterDataDefinition
    ### Type
    app.doctrine.character_data_definition.form.factory:
        class: AppBundle\Domain\CharacterDataDefinition\Form\FormFactory
        tags:
            - { name: 'mmc.processor.chain' }

    app.doctrine.character_data_definition.form.factory.boolean:
        class: AppBundle\Domain\CharacterDataDefinition\Form\BooleanFormFactory
        arguments:
            - '@form.factory'
        tags:
            - { name: 'app.doctrine.character_data_definition.form.factory' }

    app.doctrine.character_data_definition.form.factory.enum:
        class: AppBundle\Domain\CharacterDataDefinition\Form\EnumFormFactory
        arguments:
            - '@form.factory'
            - '@app.repository.character_data_definition_enum_category_item'
        tags:
            - { name: 'app.doctrine.character_data_definition.form.factory' }

    app.doctrine.character_data_definition.form.factory.integer:
        class: AppBundle\Domain\CharacterDataDefinition\Form\IntegerFormFactory
        arguments:
            - '@form.factory'
        tags:
            - { name: 'app.doctrine.character_data_definition.form.factory' }

    app.doctrine.character_data_definition.form.factory.string:
        class: AppBundle\Domain\CharacterDataDefinition\Form\StringFormFactory
        arguments:
            - '@form.factory'
        tags:
            - { name: 'app.doctrine.character_data_definition.form.factory' }

    ### Validator
    app.domain.character_data_definition.validator:
        class: AppBundle\Domain\CharacterDataDefinition\Validator\Constraints\CharacterDataDefinitionValidator
        public: false
        tags:
            - { name: 'mmc.processor.chain' }
            - { name: 'validator.constraint_validator' }

    app.domain.character_data_definition.validator.boolean:
        class: AppBundle\Domain\CharacterDataDefinition\Validator\BooleanValidator
        public: false
        tags:
            - { name: 'app.domain.character_data_definition.validator' }

    app.domain.character_data_definition.validator.enum:
        class: AppBundle\Domain\CharacterDataDefinition\Validator\EnumValidator
        public: false
        tags:
            - { name: 'app.domain.character_data_definition.validator' }

    app.domain.character_data_definition.validator.integer:
        class: AppBundle\Domain\CharacterDataDefinition\Validator\IntegerValidator
        public: false
        tags:
            - { name: 'app.domain.character_data_definition.validator' }

    app.domain.character_data_definition.validator.string:
        class: AppBundle\Domain\CharacterDataDefinition\Validator\StringValidator
        public: false
        tags:
            - { name: 'app.domain.character_data_definition.validator' }

    ### Viewer
    app.domain.character_data_definition.viewer:
        class: AppBundle\Domain\CharacterDataDefinition\Viewer\Viewer
        tags:
            - { name: 'mmc.processor.chain' }

    app.domain.character_data_definition.viewer.boolean:
        class: AppBundle\Domain\CharacterDataDefinition\Viewer\BooleanViewer
        tags:
            - { name: 'app.domain.character_data_definition.viewer' }

    app.domain.character_data_definition.viewer.enum:
        class: AppBundle\Domain\CharacterDataDefinition\Viewer\EnumViewer
        arguments:
            - '@app.repository.character_data_definition_enum_category_item'
        tags:
            - { name: 'app.domain.character_data_definition.viewer' }

    app.domain.character_data_definition.viewer.integer:
        class: AppBundle\Domain\CharacterDataDefinition\Viewer\IntegerViewer
        tags:
            - { name: 'app.domain.character_data_definition.viewer' }

    app.domain.character_data_definition.viewer.string:
        class: AppBundle\Domain\CharacterDataDefinition\Viewer\StringViewer
        tags:
            - { name: 'app.domain.character_data_definition.viewer' }

    ## Group
    app.domain.group.composition_provider:
        class: AppBundle\Domain\Group\CompositionProvider
        arguments:
            - '@app.repository.group'

    # Repository
    app.repository.character:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Character' ]

    app.repository.character_data_definition_enum_category_item:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:CharacterDataDefinitionEnumCategoryItem' ]

    app.repository.group:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Group' ]

    app.repository.larp:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Larp' ]

    app.repository.organizer:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Organizer' ]

    app.repository.person:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Person' ]

    app.repository.player:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Player' ]

    app.repository.skill:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Skill' ]
