services:
    # Domain

    ## CharacterDataDefinition
    ### Type
    app.doctrine.character_data_definition.form.factory:
        class: AppBundle\Domain\CharacterDataDefinition\Form\FormFactory
        tags:
            - { name: 'mmc.processor.chain' }

    app.doctrine.character_data_definition.form.factory.integer:
        class: AppBundle\Domain\CharacterDataDefinition\Form\IntegerFormFactory
        arguments:
            - '@form.factory'
        tags:
            - { name: 'app.doctrine.character_data_definition.form.factory' }

    app.doctrine.character_data_definition.form.factory.string:
        class: AppBundle\Domain\CharacterDataDefinition\Form\StringFormFactory
        arguments:
            - '@form.factory'
        tags:
            - { name: 'app.doctrine.character_data_definition.form.factory' }

    ### Validator
    app.domain.character_data_definition.validator:
        class: AppBundle\Domain\CharacterDataDefinition\Validator\Constraints\CharacterDataDefinitionValidator
        public: false
        tags:
            - { name: 'mmc.processor.chain' }
            - { name: 'validator.constraint_validator' }

    app.domain.character_data_definition.validator.integer:
        class: AppBundle\Domain\CharacterDataDefinition\Validator\IntegerValidator
        public: false
        tags:
            - { name: 'app.domain.character_data_definition.validator' }

    app.domain.character_data_definition.validator.string:
        class: AppBundle\Domain\CharacterDataDefinition\Validator\StringValidator
        public: false
        tags:
            - { name: 'app.domain.character_data_definition.validator' }

    ### Viewer
    app.domain.character_data_definition.viewer:
        class: AppBundle\Domain\CharacterDataDefinition\Viewer\Viewer
        tags:
            - { name: 'mmc.processor.chain' }

    app.domain.character_data_definition.viewer.integer:
        class: AppBundle\Domain\CharacterDataDefinition\Viewer\IntegerViewer
        tags:
            - { name: 'app.domain.character_data_definition.viewer' }

    app.domain.character_data_definition.viewer.string:
        class: AppBundle\Domain\CharacterDataDefinition\Viewer\StringViewer
        tags:
            - { name: 'app.domain.character_data_definition.viewer' }

    ## Group
    app.domain.group.composition_provider:
        class: AppBundle\Domain\Group\CompositionProvider
        arguments:
            - '@app.repository.group'

    # Repository
    app.repository.character:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Character' ]

    app.repository.group:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Group' ]

    app.repository.larp:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Larp' ]

    app.repository.organizer:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Organizer' ]

    app.repository.person:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Person' ]

    app.repository.player:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Player' ]

    app.repository.skill:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: 'doctrine:getRepository'
        arguments: [ 'AppBundle:Skill' ]
